[project]
name = "document-chunker"
version = "0.1.0"
description = "Converts .pdf to chunks in .md using Docling"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "docling>=2.111.0",
    "pymupdf>=1.28.0",
    "python-dotenv>=1.2.2",
    "rich>=15.0.0",
]

[tool.pyright]
extraPaths = ["."]

